package com.empowerswr.luksave.ui.theme

import androidx.compose.ui.graphics.Color

// Light Color Scheme
val PrimaryLight = Color(0xFF286776) // Slate Blue for text, headers
val OnPrimaryLight = Color(0xFFEFFBFF) // Light blue-gray for contrast
val PrimaryContainerLight = Color(0xFFB0ECFE) // Light blue for tonal elements
val OnPrimaryContainerLight = Color(0xFF155968) // Dark blue for text/icons
val InversePrimaryLight = Color(0xFFBF6F00) // Orange as inverse (for buttons if needed)
val SecondaryLight = Color(0xFF2D6B40) // Muted Lime Green
val OnSecondaryLight = Color(0xFFE8FFE8) // Light green for contrast
val SecondaryContainerLight = Color(0xFFBBFEC6) // Light green container
val OnSecondaryContainerLight = Color(0xFF266439) // Dark green for text/icons
val TertiaryLight = Color(0xFF735D00) // Muted orange as tertiary
val OnTertiaryLight = Color(0xFFFFF8EE) // Light cream for contrast
val TertiaryContainerLight = Color(0xFFFDDA64) // Light orange container
val OnTertiaryContainerLight = Color(0xFF5F4C00) // Dark amber for text/icons
val BackgroundLight = Color(0xFFF8FBFF) // Lighter blue-gray background
val OnBackgroundLight = Color(0xFF003748) // Dark blue for headers/text
val SurfaceLight = Color(0xFFF8FBFF) // Lighter surface for cards
val OnSurfaceLight = Color(0xFF003748) // Dark blue for card text/headers
val SurfaceVariantLight = Color(0xFFE7F0F8) // Lighter variant for cards
val OnSurfaceVariantLight = Color(0xFF32657A) // Dark blue-gray for icons/text
val SurfaceTintLight = Color(0xFF286776) // Slate Blue tint
val InverseSurfaceLight = Color(0xFF001018) // Dark inverse surface
val InverseOnSurfaceLight = Color(0xFF87A1AE) // Light gray for inverse text
val ErrorLight = Color(0xFFFF1744) // Vibrant red for borders
val OnErrorLight = Color(0xFFFFFFFF) // White for high-contrast error text
val ErrorContainerLight = Color(0xFFFF8A80) // Light red for alert background
val OnErrorContainerLight = Color(0xFF410002) // Dark red for text/icons
val OutlineLight = Color(0xFF508197) // Blue-gray for card outlines
val OutlineVariantLight = Color(0xFF87B9D0) // Lighter blue-gray outline
val ScrimLight = Color(0xFF000000) // Black for scrims
val SurfaceBrightLight = Color(0xFFFFFFFF) // Brightest surface
val SurfaceContainerLight = Color(0xFFF0F5FF) // Lighter container for cards
val SurfaceContainerHighLight = Color(0xFFEAF1FA) // Slightly darker container
val SurfaceContainerHighestLight = Color(0xFFE7F0F8) // Matches surface variant
val SurfaceContainerLowLight = Color(0xFFF8FBFF) // Matches surface
val SurfaceContainerLowestLight = Color(0xFFFFFFFF) // Pure white
val SurfaceDimLight = Color(0xFFE7F0F8) // Dimmed surface for cards

// Dark Color Scheme
val PrimaryDark = Color(0xFF80B8D8) // Slate Blue for text, headers
val OnPrimaryDark = Color(0xFF0A2B3A) // Dark navy for contrast
val PrimaryContainerDark = Color(0xFF4A829F) // Muted blue for tonal elements
val OnPrimaryContainerDark = Color(0xFFD9EFFF) // Light blue-gray for text/icons
val InversePrimaryDark = Color(0xFFFFA726) // Orange as inverse (for buttons if needed)
val SecondaryDark = Color(0xFFA8D5A8) // Muted Lime Green
val OnSecondaryDark = Color(0xFF1A3C1A) // Dark green for contrast
val SecondaryContainerDark = Color(0xFF355935) // Dark muted green
val OnSecondaryContainerDark = Color(0xFFC5E7C5) // Light green for text/icons
val TertiaryDark = Color(0xFFF4C77A) // Muted orange as tertiary
val OnTertiaryDark = Color(0xFF3D2F00) // Dark amber for contrast
val TertiaryContainerDark = Color(0xFF8B6F00) // Darker orange container
val OnTertiaryContainerDark = Color(0xFFFFE8B0) // Light orange for text/icons
val BackgroundDark = Color(0xFF121D24) // Lighter blue-gray background
val OnBackgroundDark = Color(0xFFDDE8F0) // Light gray-blue for headers/text
val SurfaceDark = Color(0xFF1B2A33) // Lighter surface for cards
val OnSurfaceDark = Color(0xFFDDE8F0) // Light gray-blue for card text/headers
val SurfaceVariantDark = Color(0xFF2E3F4A) // Lighter variant for cards
val OnSurfaceVariantDark = Color(0xFFB0C6D3) // Light gray for icons/text
val SurfaceTintDark = Color(0xFF80B8D8) // Slate Blue tint
val InverseSurfaceDark = Color(0xFFDDE8F0) // Light surface for contrast
val InverseOnSurfaceDark = Color(0xFF2A3A44) // Darker gray for inverse text
val ErrorDark = Color(0xFFFFB4AB) // Bright red for borders
val OnErrorDark = Color(0xFF690005) // Dark red for high-contrast error text
val ErrorContainerDark = Color(0xFF93000A) // Dark red for alert background
val OnErrorContainerDark = Color(0xFFFFDAD6) // Light red for text/icons
val OutlineDark = Color(0xFF6B8290) // Blue-gray for card outlines
val OutlineVariantDark = Color(0xFF3E5666) // Darker blue-gray outline
val ScrimDark = Color(0xFF000000) // Black for scrims
val SurfaceBrightDark = Color(0xFF263842) // Slightly brighter surface
val SurfaceContainerDark = Color(0xFF1E2B34) // Lighter container for cards
val SurfaceContainerHighDark = Color(0xFF263842) // Slightly elevated container
val SurfaceContainerHighestDark = Color(0xFF2E3F4A) // Matches surface variant
val SurfaceContainerLowDark = Color(0xFF1B2A33) // Matches surface
val SurfaceContainerLowestDark = Color(0xFF0D161B) // Darkest surface
val SurfaceDimDark = Color(0xFF121D24) // Dimmed surface for cards